# Generated by Django 3.2.3 on 2021-06-08 10:24
import datetime
import json
import os

from django.db import migrations, transaction

FILE_PATH = 'mainapp/json'


def load_from_json(filename):
    with open(os.path.join(FILE_PATH, filename), encoding='utf-8') as json_file:
        return json.load(json_file)


def fill_db_fake_data(apps, schema_editor):
    students = load_from_json('students.json')
    teachers = load_from_json('teachers.json')
    homeworks = load_from_json('homeworks.json')
    homework_results = load_from_json('homework_results.json')
    student_model = apps.get_model("mainapp", "Student")
    teacher_model = apps.get_model("mainapp", "Teacher")
    homework_model = apps.get_model("mainapp", "Homework")
    homework_result_model = apps.get_model("mainapp", "HomeworkResult")
    for teacher in teachers:
        with transaction.atomic():
            teacher_model.objects.create(**teacher)
    for student in students:
        with transaction.atomic():
            student_model.objects.create(**student)
    for homework in homeworks:
        with transaction.atomic():
            homework_creator = homework['teacher']
            deadline = homework['deadline']
            deadline = datetime.timedelta(days=deadline)
            _teacher = teacher_model.objects.get(pk=homework_creator)
            homework['deadline'] = deadline
            homework['teacher'] = _teacher
            homework_model.objects.create(**homework)

    for result in homework_results:
        with transaction.atomic():
            result_creator = result['student']
            _student = student_model.objects.get(pk=result_creator)
            result_task = result['homework']
            _homework = homework_model.objects.get(pk=result_task)
            result['homework'] = _homework
            result['student'] = _student
            homework_result_model.objects.create(**result)


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(fill_db_fake_data)
    ]
